//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 10:57:20 PM CEST 
//


package org.kodoliti.fluid.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tChoreography complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tChoreography">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tCollaboration">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}flowElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tChoreography", propOrder = {
    "flowElement"
})
@XmlSeeAlso({
    TGlobalChoreographyTask.class
})
public class TChoreography
    extends TCollaboration
{

    @XmlElementRef(name = "flowElement", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TFlowElement>> flowElement;

    /**
     * Gets the value of the flowElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlowElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TManualTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBoundaryEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TImplicitThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TChoreographyTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TParallelGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TDataObject }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TEndEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TIntermediateThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TFlowElement }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSequenceFlow }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TReceiveTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TAdHocSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallActivity }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TUserTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TServiceTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TDataStoreReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBusinessRuleTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TInclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TStartEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TComplexGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTransaction }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSendTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TEventBasedGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TExclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TDataObjectReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSubChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TIntermediateCatchEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TScriptTask }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TFlowElement>> getFlowElement() {
        if (flowElement == null) {
            flowElement = new ArrayList<JAXBElement<? extends TFlowElement>>();
        }
        return this.flowElement;
    }

}
