//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 10:57:20 PM CEST 
//


package org.kodoliti.fluid.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for tProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tProcess">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tCallableElement">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}auditing" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}monitoring" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}laneSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}flowElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}artifact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}resourceRole" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}correlationSubscription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="supports" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="processType" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tProcessType" default="None" />
 *       &lt;attribute name="isClosed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isExecutable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="definitionalCollaborationRef" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tProcess", propOrder = {
    "auditing",
    "monitoring",
    "property",
    "laneSet",
    "flowElement",
    "artifact",
    "resourceRole",
    "correlationSubscription",
    "supports"
})
public class TProcess
    extends TCallableElement
{

    protected TAuditing auditing;
    protected TMonitoring monitoring;
    protected List<TProperty> property;
    protected List<TLaneSet> laneSet;
    @XmlElementRef(name = "flowElement", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TFlowElement>> flowElement;
    @XmlElementRef(name = "artifact", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TArtifact>> artifact;
    @XmlElementRef(name = "resourceRole", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TResourceRole>> resourceRole;
    protected List<TCorrelationSubscription> correlationSubscription;
    protected List<QName> supports;
    @XmlAttribute(name = "processType")
    protected TProcessType processType;
    @XmlAttribute(name = "isClosed")
    protected Boolean isClosed;
    @XmlAttribute(name = "isExecutable")
    protected Boolean isExecutable;
    @XmlAttribute(name = "definitionalCollaborationRef")
    protected QName definitionalCollaborationRef;

    /**
     * Gets the value of the auditing property.
     * 
     * @return
     *     possible object is
     *     {@link org.kodoliti.fluid.model.TAuditing }
     *     
     */
    public TAuditing getAuditing() {
        return auditing;
    }

    /**
     * Sets the value of the auditing property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.kodoliti.fluid.model.TAuditing }
     *     
     */
    public void setAuditing(TAuditing value) {
        this.auditing = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link org.kodoliti.fluid.model.TMonitoring }
     *     
     */
    public TMonitoring getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.kodoliti.fluid.model.TMonitoring }
     *     
     */
    public void setMonitoring(TMonitoring value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TProperty }
     * 
     * 
     */
    public List<TProperty> getProperty() {
        if (property == null) {
            property = new ArrayList<TProperty>();
        }
        return this.property;
    }

    /**
     * Gets the value of the laneSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the laneSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaneSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.kodoliti.fluid.model.TLaneSet }
     * 
     * 
     */
    public List<TLaneSet> getLaneSet() {
        if (laneSet == null) {
            laneSet = new ArrayList<TLaneSet>();
        }
        return this.laneSet;
    }

    /**
     * Gets the value of the flowElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlowElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TManualTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBoundaryEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TImplicitThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TChoreographyTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TParallelGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataObject }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEndEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TIntermediateThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TFlowElement }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSequenceFlow }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TReceiveTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TAdHocSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallActivity }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TUserTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TServiceTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataStoreReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBusinessRuleTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TInclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TStartEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TComplexGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTransaction }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSendTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEventBasedGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TExclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataObjectReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TSubChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TIntermediateCatchEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TScriptTask }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TFlowElement>> getFlowElement() {
        if (flowElement == null) {
            flowElement = new ArrayList<JAXBElement<? extends TFlowElement>>();
        }
        return this.flowElement;
    }

    /**
     * Gets the value of the artifact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TAssociation }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTextAnnotation }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TArtifact }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TGroup }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TArtifact>> getArtifact() {
        if (artifact == null) {
            artifact = new ArrayList<JAXBElement<? extends TArtifact>>();
        }
        return this.artifact;
    }

    /**
     * Gets the value of the resourceRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TResourceRole }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TPerformer }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.THumanPerformer }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TPotentialOwner }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TResourceRole>> getResourceRole() {
        if (resourceRole == null) {
            resourceRole = new ArrayList<JAXBElement<? extends TResourceRole>>();
        }
        return this.resourceRole;
    }

    /**
     * Gets the value of the correlationSubscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correlationSubscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrelationSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.kodoliti.fluid.model.TCorrelationSubscription }
     * 
     * 
     */
    public List<TCorrelationSubscription> getCorrelationSubscription() {
        if (correlationSubscription == null) {
            correlationSubscription = new ArrayList<TCorrelationSubscription>();
        }
        return this.correlationSubscription;
    }

    /**
     * Gets the value of the supports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.namespace.QName }
     * 
     * 
     */
    public List<QName> getSupports() {
        if (supports == null) {
            supports = new ArrayList<QName>();
        }
        return this.supports;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link TProcessType }
     *     
     */
    public TProcessType getProcessType() {
        if (processType == null) {
            return TProcessType.NONE;
        } else {
            return processType;
        }
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProcessType }
     *     
     */
    public void setProcessType(TProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the isClosed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsClosed() {
        if (isClosed == null) {
            return false;
        } else {
            return isClosed;
        }
    }

    /**
     * Sets the value of the isClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsClosed(Boolean value) {
        this.isClosed = value;
    }

    /**
     * Gets the value of the isExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsExecutable() {
        return isExecutable;
    }

    /**
     * Sets the value of the isExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExecutable(Boolean value) {
        this.isExecutable = value;
    }

    /**
     * Gets the value of the definitionalCollaborationRef property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.namespace.QName }
     *     
     */
    public QName getDefinitionalCollaborationRef() {
        return definitionalCollaborationRef;
    }

    /**
     * Sets the value of the definitionalCollaborationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.namespace.QName }
     *     
     */
    public void setDefinitionalCollaborationRef(QName value) {
        this.definitionalCollaborationRef = value;
    }

}
