//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 10:57:20 PM CEST 
//


package org.kodoliti.fluid.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSubProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSubProcess">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tActivity">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}laneSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}flowElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/MODEL}artifact" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="triggeredByEvent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSubProcess", propOrder = {
    "laneSet",
    "flowElement",
    "artifact"
})
@XmlSeeAlso({
    TAdHocSubProcess.class,
    TTransaction.class
})
public class TSubProcess
    extends TActivity
{

    protected List<TLaneSet> laneSet;
    @XmlElementRef(name = "flowElement", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TFlowElement>> flowElement;
    @XmlElementRef(name = "artifact", namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends TArtifact>> artifact;
    @XmlAttribute(name = "triggeredByEvent")
    protected Boolean triggeredByEvent;

    /**
     * Gets the value of the laneSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the laneSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaneSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.kodoliti.fluid.model.TLaneSet }
     * 
     * 
     */
    public List<TLaneSet> getLaneSet() {
        if (laneSet == null) {
            laneSet = new ArrayList<TLaneSet>();
        }
        return this.laneSet;
    }

    /**
     * Gets the value of the flowElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlowElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TManualTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBoundaryEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TImplicitThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TChoreographyTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TParallelGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataObject }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEndEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TIntermediateThrowEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TFlowElement }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TSequenceFlow }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TReceiveTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TAdHocSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TCallActivity }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TUserTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TServiceTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TSubProcess }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataStoreReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TBusinessRuleTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TInclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TStartEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TComplexGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTransaction }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TSendTask }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TEventBasedGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TExclusiveGateway }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TDataObjectReference }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TSubChoreography }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TIntermediateCatchEvent }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TScriptTask }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TFlowElement>> getFlowElement() {
        if (flowElement == null) {
            flowElement = new ArrayList<JAXBElement<? extends TFlowElement>>();
        }
        return this.flowElement;
    }

    /**
     * Gets the value of the artifact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TAssociation }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TTextAnnotation }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TArtifact }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link org.kodoliti.fluid.model.TGroup }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TArtifact>> getArtifact() {
        if (artifact == null) {
            artifact = new ArrayList<JAXBElement<? extends TArtifact>>();
        }
        return this.artifact;
    }

    /**
     * Gets the value of the triggeredByEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTriggeredByEvent() {
        if (triggeredByEvent == null) {
            return false;
        } else {
            return triggeredByEvent;
        }
    }

    /**
     * Sets the value of the triggeredByEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTriggeredByEvent(Boolean value) {
        this.triggeredByEvent = value;
    }

}
